apiVersion: v1
kind: Secret
metadata:
  name: quay-registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRGM9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXsample
type: kubernetes.io/dockerconfigjson

